### ISSUE TITLE
[BUG] Doesn't auto update with the French regional format in Windows 10

### ISSUE THREAD

**Issue by Fotia13** [TopazTK/KH-ReFixed#24]
**Re:Fixed Version:**
v2.10 - Stable

**Game in Question:**
Kingdom Hearts II - Final Mix [v1.0.1.2]

**Bug Description:**
When running the exe the error "Re:Fixed was not able to check for updates. Initializing the game normally..."

**Reproduction Steps:**
In Windows settings > Time & Language > Region > Regional Format > French (France)

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by TopazTK** [comment]
Err, this should not happen considering I had people with French copies of Windows update no problem.
But I will check it out.

**Comment by Fotia13** [comment]
> Err, this should not happen considering I had people with French copies of Windows update no problem.
> But I will check it out.

Can it be due to the jack sparrow version of KH ?
Or the Windows professional version ?

**Comment by TopazTK** [comment]
Neither. Check your internet and firewall.

**Comment by TopazTK** [comment]
That is... odd. I will check this out. But in the meantime, you can use manual updating if needed.

**Comment by Doomsday33** [comment]
Had the same issue. Using French Canadian regional format here.

Did some digging around and found out the culprit was the decimal symbol for the numbers. French and french canadian are using « , » (comma) instead of « . » (point/dot). The updater works if I only change the comma for a point in the panel here.

So I'm guessing the updater has some kind of  hard coded lookup for some decimal number using a « . » instead of getting through the OS regional format for decimal symbol.

Hope this helps.

![decimal regional format french](https://user-images.githubusercontent.com/107327989/173208117-9f883536-1739-49df-ba33-cecd7bc0f44c.png)

**Comment by TopazTK** [comment]
Octokit is gay.

**Comment by TopazTK** [comment]
Addressed with upcoming v2.90.
Closing.
