### ISSUE TITLE
Automatic Retry Bug

### ISSUE THREAD

**Issue by PewDeiPei** [TopazTK/KH-ReFixed#43]
So far I have beast's castle beaten and the auto retry hasn't occurred during any of the bosses, but on Shan-Yu the battle keeps retrying after I defeat him and if I beat him again on the second time after the first retry it will retry again and again

https://user-images.githubusercontent.com/99282955/173927140-ce8a0e03-882e-4d1b-8992-360150889334.mp4

**Comment by aichi-n-crew** [comment]
the way it just fluently transitions as if you never fought him.
maybe try to undo the mod and beat it as normal then reinstall it to get past it for the time being

**Comment by PewDeiPei** [comment]
Okay i'll try that for now, thank you

**Comment by TopazTK** [comment]
Yea, do that for now. For some reason Shan-Yu is being a terrible exception.
Will see what's up with that.

**Comment by TopazTK** [comment]
Was able to reproduce, now just gotta know WHY it happens.

**Comment by TopazTK** [comment]
The problem only occurs if Mickey is summoned, as the game does not know that Sora came back to life with Mickey.
To combat this, the functions will be restored if Sora's form parameter is set to "MICKEY", and as a precaution, if the "BATTLE_FINISH" is set to "TRUE".

Will push the changes, the bug has been addressed, the issue is now closed.
